# [Image Semantic Segmentation using Gaussian Mixture Model]

This project utilizes a chosen image to perform image semantic segmentation using the Gaussian Mixture Model from the sklearn library.

# 1. Project Introduction
The Gaussian Mixture Model is a clustering algorithm that can perform basic semantic segmentation operations on images.

Additionally, we also employed the K-means model for semantic segmentation to compare segmentation results.

We will also validate the effectiveness of the Gaussian Mixture Model in data generation. Utilizing the trained Gaussian Mixture Model, we generate pixel samples.

The segmentation results and generated pixel points are illustrated in the accompanying figures.

![](https://ai-studio-static-online.cdn.bcebos.com/8235e213370a4c86926d812a56e435b5acc13b8bc4ea4dea8af79ecf4b8bde76)


# 2. Project Analysis and Solution Design

In this project, we first read in the image and perform data preprocessing. Then, we create a Gaussian Mixture Model class, initiate fitting, and utilize the Gaussian Mixture Model to accomplish image segmentation.

In addition to the Gaussian Mixture Model, we also utilized the K-means model for image semantic segmentation. Finally, we generate pixel samples using the model fitted by the Gaussian Mixture Model.

The project steps can be summarized briefly as shown in the flowchart.


# 3. Project Preparation
Before beginning the experiment, we need to prepare the experimental environment to ensure smooth progress. This experiment will be implemented using AIStudio, and the configuration of the experimental environment is as follows:
    
    
| Name         | Version | Function Description                                           |
|--------------|---------|--------------------------------------------------------------|
| AIStudio     | Classic | Foundational platform and environment for code implementation|
| PaddlePaddle | 2.1.2   | Fundamental APIs for deep learning technologies              |
| Python       | 3.7     | Programming language                                          |
| cv2          | Default | Python library for OpenCV, extensively used in computer vision|
| Os           | Default | Module in Python standard library for accessing OS functions  |
| numpy        | Default | Library for scientific computing in Python, widely used in data analysis|
| matplotlib   | Default | Plotting library for Python                                   |
| sklearn      | Default | Scikit-learn, a powerful machine learning library            |


# 4. Code Implementation

## 4.1 Environment Import

In [1]:
import cv2  # Python package for OpenCV, used for image processing
import os  # Module in Python standard library for accessing OS functions
import numpy as np  # Library for scientific computing in Python, widely used in data analysis
import matplotlib.pyplot as plt  # Plotting library for Python
from sklearn.mixture import GaussianMixture  # Gaussian Mixture Model from sklearn
from numpy import *
from PIL import Image, ImageDraw  # PIL for image processing

## 4.2 Image Reading and Preprocessing
We continue to process the image data by first using the imread() function to read the image to be processed, and then using the reshape() function to flatten the pixel matrix of the image from two dimensions to one dimension for processing.

In [2]:
# Gaussian Mixture Model
picPath = "test1.jpg"  # Path to the image
pic = plt.imread(picPath)  # Read the image
pic.shape

(700, 700, 3)

In [3]:
img = pic.reshape((pic.shape[0]*pic.shape[1], 3))  # Reshape to an array
img.shape

(490000, 3)

## 4.3 Data Processing Using Gaussian Mixture Model
Create a Gaussian Mixture Model class using GaussianMixture().

The parameters and their meanings are as follows:

| Parameter Name  | Meaning                                              |
|-----------------|------------------------------------------------------|
| n_components    | Number of Gaussian models in the Gaussian Mixture Model|
| covariance_type | String setting describing the type of covariance parameters to be used, set to 'diag'|
| random_state    | Random seed provided to the initialization method, set to 0|


In [4]:
k = 10  # Number of Gaussian models in the Gaussian Mixture Model
GMM = GaussianMixture(n_components=k, covariance_type='diag', random_state=0)  # Create Gaussian Mixture Model
GMM.fit(img)  # Begin fitting the Gaussian Mixture Model
print(GMM.covariances_)  # Print covariances
print(GMM.means_)  # Print means

[[ 364.38382016   58.14315955   33.57131739]
 [  96.69855638   32.90549222   38.14720377]
 [ 182.54475685   99.72096489   51.7433728 ]
 [  30.15091552  109.31817841   23.11310615]
 [1085.27635175  113.45386949   88.07127419]
 [ 329.01293043  280.45512539   97.85307262]
 [ 212.41572044   32.28477158   32.85523843]
 [ 592.41019216  180.49976438  140.35356116]
 [ 183.38044058   39.4997433    65.49922094]
 [ 126.00347738   86.52506422   28.04164415]]
[[166.76528741 161.88385722 146.04823286]
 [ 22.53365146  15.97616581  12.50961547]
 [ 61.41696086 131.64760959  91.96569208]
 [221.54917792 190.86603743 174.63935604]
 [166.68077013  48.31391517  39.41156577]
 [ 31.02417401  68.49123771  45.65368879]
 [124.24516744 127.98297373 110.82801488]
 [ 90.98890387  94.34930068  75.83996591]
 [ 71.77241781 150.18038234 110.27810326]
 [ 36.1746828  106.61516058  69.09986022]]


## 4.4 Image Segmentation Using Gaussian Mixture Model
First, use GMM.predict() to obtain the classification labels of the original data by the Gaussian Mixture Model.

Use nested loops to obtain the feature coordinates of the cluster centers, and then use nested loops again to assign the coordinates of the pixel labels of the cluster centers to new_image. Finally, save and output the new_image image.

The result is saved in k_GMM_k=xx.jpg.

In [5]:
labels = GMM.predict(img)  # Obtain classification labels by the Gaussian Mixture Model for the original data
labels[1000:2000]

array([6, 6, 6, 9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 9, 9, 1, 1, 1,
       1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,

In [6]:
height = pic.shape[0]  # Get the height of the image
width = pic.shape[1]  # Get the width of the image
new_image = np.zeros((height,width,3), np.uint8)  # Create a blank matrix according to the original image size to store the segmented image
center = np.zeros([k, 3])  # Create an empty matrix to store the color vectors for each class
for i in range(k):
    for j in range(3):
        # Iterate through all k classes and compute the color vectors for each class
        center[i, j] = GMM.means_[i, j]
center = center.astype(np.int32)  # Since color encoding is of integer type, type conversion is required
label = labels.reshape((height, width))  # Reshape the label originally arranged in one dimension to the same shape as the image

print(label.shape)
print(label)
print(center.shape)
print(center)

(700, 700)
[[6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 ...
 [3 3 3 ... 6 6 6]
 [3 3 3 ... 6 6 6]
 [3 3 3 ... 6 6 6]]
(10, 3)
[[166 161 146]
 [ 22  15  12]
 [ 61 131  91]
 [221 190 174]
 [166  48  39]
 [ 31  68  45]
 [124 127 110]
 [ 90  94  75]
 [ 71 150 110]
 [ 36 106  69]]


In [7]:
for i in range(0, height):
    for j in range(0, width): # Double loop to iterate through each position in the image
        new_image[i,j] = center[label[i][j]] # Assign color values to each pixel of the image, the value is represented by the pixel's belonging cluster center
cv2.imwrite('k_GMM_k={:d}.jpg'.format(k), new_image)  # Store the obtained clustered image

True

## 4.5 Image Segmentation Using K-means Model
Next, we will perform image segmentation using the K-means model. The code is similar to the previous section, with the only difference being the model training part.

The result is saved in kmeans_k=xx.jpg.

In [8]:
from sklearn.cluster import KMeans  # Importing the k-means model
picPath = "test1.jpg"  # Path to the image
pic = plt.imread(picPath)  # Read the image from the path
img = pic.reshape((pic.shape[0]*pic.shape[1], 3))  # Reshape and store as an array, the shape of the array is (height * width, 3)
print(img.shape)

(490000, 3)


In [9]:
k = 10  # Set the number of clusters
kmeans = KMeans(n_clusters=k, init='k-means++')  # Use k-means++ to select initial cluster centers, build kmeans
kmeans.fit(img)  # Train using the .fit method
print(kmeans.labels_)
print(kmeans.cluster_centers_)

[2 2 2 ... 9 9 9]
[[ 23.44976297  16.97249412  13.24937758]
 [214.37868329 179.58202825 167.98066503]
 [ 38.26084311 107.6826323   70.58081628]
 [175.42936523  48.35414903  39.28853726]
 [226.20213194 201.23155826 178.84706665]
 [120.08716408 125.08354253 107.22992716]
 [160.2286472  159.31710329 143.94665133]
 [ 90.51932219  71.83215764  58.02952001]
 [ 25.98584827  72.05585989  47.33208831]
 [ 66.04085028 139.13182251  99.10080925]]


In [10]:
height = pic.shape[0]  # Store the length of the image
width = pic.shape[1]  # Store the width of the image
new_image = np.zeros((height,width,3), np.uint8)  # Create a blank matrix with the same size as the original image using numpy
center = np.zeros([k, 3])  # Create a blank matrix using numpy to store cluster centers
for i in range(k):
    for j in range(3):
        # Double loop to obtain the feature coordinates of the cluster centers
        center[i, j] = kmeans.cluster_centers_[i, j]
center = center.astype(np.int32)  # Since color encoding is of integer type, type conversion is required
label = kmeans.labels_
label = label.reshape((height, width))  # Reshape the label originally arranged in one dimension to the same shape as the image
for i in range(0, height):
    for j in range(0, width):
        # Double loop to iterate through each position in the image
        new_image[i,j] = center[label[i][j]]  # Assign color values to each pixel of the image, the value is represented by the pixel's belonging cluster center
# print(new_image)
cv2.imwrite('kmeans_k={:d}.jpg'.format(k), new_image)  # Store the obtained clustered image

True

## 4.6 Generating Samples Using Gaussian Mixture Model
Use the sample() method to generate samples using the trained Gaussian Mixture Model. Convert the generated samples to integer type using np.array(). Finally, use reshape() to arrange the pixels in one image and save the output result image.

The result is saved in GEN_GMM_k=xx.jpg.

In [11]:
height = pic.shape[0]  # Get the height of the image
width = pic.shape[1]  # Get the width of the image
img_new = np.zeros((height,width,3), np.uint8)  # Create a blank matrix with the same size as the original image to store the new image
data_new = GMM.sample(height * width)  # Use the trained Gaussian Mixture Model, same number of pixels as the original image
print(data_new)

(array([[195.28552408, 160.31949136, 147.86217094],
       [150.46159033, 142.41688557, 149.83534872],
       [183.26637187, 156.22472559, 159.19936379],
       ...,
       [ 21.7007864 , 115.29646684,  70.35174087],
       [ 47.55503149, 114.5691838 ,  70.35578417],
       [ 33.67062399, 116.92707725,  71.24621852]]), array([0, 0, 0, ..., 9, 9, 9]))


In [12]:
data_new = np.array(data_new[0]).astype(np.int32)  # Process the generated data, convert to integer type
print(data_new)

[[195 160 147]
 [150 142 149]
 [183 156 159]
 ...
 [ 21 115  70]
 [ 47 114  70]
 [ 33 116  71]]


In [13]:
data_new = data_new.reshape((height, width, 3))  # Arrange the pixels in one image
cv2.imwrite('GEN_GMM_k={:d}.jpg'.format(k), data_new)  # Save and output the experimental results

True